# Generated by Django 6.0.5 on 2026-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Document', 'Document'), ('Conversion', 'Conversion'), ('User', 'User'), ('Quality', 'Quality')], max_length=30)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
