# Generated by Django 6.0.5 on 2026-05-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_initial'),
        ('documents_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets_app.asset'),
        ),
    ]
