# Generated by Django 6.0.5 on 2026-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('cadquery_code', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('STEP', 'STEP'), ('STL', 'STL'), ('GLTF', 'GLTF'), ('PY', 'Python/CadQuery')], max_length=10)),
                ('file', models.FileField(upload_to='models3d/')),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'models3d',
                'ordering': ['-created_at'],
            },
        ),
    ]
