# Generated by Django 6.0.5 on 2026-05-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversions_app', '0001_initial'),
        ('documents_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='documents_app.document'),
        ),
    ]
