# Generated by Django 6.0.5 on 2026-05-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversions_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model3d',
            name='conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='conversions_app.conversion'),
        ),
    ]
