# Generated by Django 6.0.5 on 2026-05-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversions_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_valid', models.BooleanField(default=False)),
                ('geometry_valid', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0.0)),
                ('flag_status', models.CharField(choices=[('none', 'None'), ('flagged', 'Flagged'), ('resolved', 'Resolved')], default='none', max_length=20)),
                ('flag_comment', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='conversions_app.conversion')),
            ],
            options={
                'db_table': 'quality_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
